server:
  port: ${SERVER-PORT:8080}

spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://${DB-URL}/kanbanboard
    username: ${DB-USER}
    password: ${DB-PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        connection:
          CharSet: utf-8
          characterEncoding: utf-8
          useUnicode: true
jwt-secret-key: ${JWT-KEY}

