### 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username":"{{username}}",
  "password":"{{password}}"
}

> {%
  client.log(response.headers.valueOf("AccessToken"));
  client.log(response.headers.valueOf("RefreshToken"));
  client.global.set("AccessToken", response.headers.valueOf("AccessToken"));
  client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
%}

### 보드 생성
POST http://localhost:8080/boards
AccessToken: {{AccessToken}}
Content-Type: application/json

{
  "name" : "board1",
  "explanation" : "board1"
}

### 보드 조회
GET http://localhost:8080/boards
AccessToken: {{AccessToken}}
Content-Type: application/json

### 보드 수정
PATCH http://localhost:8080/boards/3
AccessToken: {{AccessToken}}
Content-Type: application/json

{
  "name" : "board",
  "explanation" : "board"
}

### 보드 삭제
DELETE http://localhost:8080/boards/2
AccessToken: {{AccessToken}}
Content-Type: application/json

### 보드 초대
POST http://localhost:8080/boards/1/invite/2
AccessToken: {{AccessToken}}
Content-Type: application/json