### 유저 회원 가입
POST http://localhost:8080/users
Content-Type: application/json

{
  "username":"{{username}}",
  "password":"{{password}}",
  "name":"{{name}}",
  "email":"{{email}}"
}

### 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username":"{{username}}",
  "password":"{{password}}"
}

> {%
  client.log(response.headers.valueOf("AccessToken"));
  client.log(response.headers.valueOf("RefreshToken"));
  client.global.set("AccessToken", response.headers.valueOf("AccessToken"));
  client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
%}

### 역할 바꾸기
PATCH http://localhost:8080/users/subscription
AccessToken: {{AccessToken}}
Content-Type: application/json

### 보드 생성
POST http://localhost:8080/boards
AccessToken: {{AccessToken}}
Content-Type: application/json

{
  "name" : "이름",
  "explanation" : "내용"
}

### 칼럼생성
POST http://localhost:8080/column/1
AccessToken: {{AccessToken}}
Content-Type: application/json

{
  "name" : "test"
}

### 카드 생성
POST http://localhost:8080/cards
AccessToken: {{AccessToken}}
Content-Type: application/json

{
  "title": "테스트 카드",
  "contents": "카드 내용",
  "columnId": 1
}

### 댓글 생성
POST http://localhost:8080/comments/1
AccessToken: {{AccessToken}}
Content-Type: application/json

{
  "content": "댓글 내용2"
}

### 댓글 조회
GET http://localhost:8080/comments/1
AccessToken: {{AccessToken}}
Content-Type: application/json

### 댓글 수정
PATCH http://localhost:8080/comments/1
AccessToken: {{AccessToken}}
Content-Type: application/json

{
  "content" : "댓글 수정"
}

### 댓글 삭제
DELETE http://localhost:8080/comments/1
AccessToken: {{AccessToken}}
Content-Type: application/json